Don't call "Q_OBJECT" if there are no signals or slots defined.
Fix cmake (and possibly autotools) build for:

lib/libqtui.a(interface_tree.cpp.o): In function `SparkLineDelegate':
/home/jmayer/work/wireshark/svn/trunk/ui/qt/sparkline_delegate.h:10: undefined reference to `vtable for SparkLineDelegate'

This would not show up using qtcreator due to the magic of qmake.

I must admit that I don't fully understand what I am doing here, but
I read the following thread to the bottom and one of the last posts
contained the solution:
http://stackoverflow.com/questions/1095298/gcc-c-linker-errors-undefined-reference-to-vtable-for-xxx-undefined-refere



git-svn-id: http://anonsvn.wireshark.org/wireshark/trunk@44280 f5534014-38df-0310-8fa8-9805f1628bb7